# Format notes:
# - Use [] for arrays instead of YAML dash-lists (except for file paths which use dash-lists for clarity)
# - Keep arrays on single line if short (e.g. [1, 2, 3])
# - For long arrays, use multiple items per line with proper indentation
# - String arrays should use quotes for consistency

display:
  windowed_width: 1024
  windowed_height: 600
  fps: 30
render:
  width: 640
  height: 360
  background_color: [25, 25, 25]
  clip_skip: 0
  background_darkness_variation: 0.1
  checkpoint: models/revAnimated_v2Rebirth.safetensors
  checkpoints:
    - models/abstractPhoto_abcevereMix.safetensors
    - models/revAnimated_v2Rebirth.safetensors
  contrast_levels: {
    "High": [25, 25, 25],
    "Medium": [45, 45, 45],
    "Low": [60, 60, 60]
  }
  models:
    vae: stabilityai/sd-vae-ft-mse
    controlnet: lllyasviel/control_v11f1e_sd15_tile
    default_model:
      url: https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned.safetensors
      path: models/sd-v1-5.safetensors
  generation:
    num_inference_steps: 12
    guidance_scale: 7
    controlnet_conditioning_scale: 1.0
    control_guidance_start: 0.15
    control_guidance_end: 0.9
system:
  shutdown_cmd: sudo /sbin/shutdown -h now
  restart_cmd: sudo /sbin/shutdown -r now
clock:
  radius_margin: 20
  marker_length: 30
  hour_hand_length_ratio: 0.7
  minute_hand_length_ratio: 0.9
  second_hand_length_ratio: 0.9
  numbered_hand_reduction: 0.2
  overlay_opacity: 75
  hour_hand_width: [24, 1]
  minute_hand_width: [16, 1]
  second_hand_width: [4, 1]
  marker_width: 3
  use_numbers: true
  font_size: 58
  display_mode: render_only
animation:
  transition_duration: 3.0
  background_update_interval: 15
  morph_flow_params:
    pyr_scale: 0.5
    levels: 3
    winsize: 15
    iterations: 3
    poly_n: 5
    poly_sigma: 1.2
    flags: 256
prompts:
  use_enhanced_prompts: true
  enhancer:
    model: "prithivMLmods/Stark-Prompt-Extender"
    max_length: 100
    max_time: 3
    temperature: 0.9
    top_p: 0.9
    num_return_sequences: 1
    do_sample: true
  enabled_styles: [digital_art, concept_art, photo, anime, renaissance, painting, watercolor, minimalist, pixel_art]
  negative_prompt: >
    asian, impossible, (worst quality, low quality)++, nude, naked, watermark,  signature,
    flower, facial marking, (women)++, (female)++,  blue jeans, 3d, render, doll,
    plastic, blur, haze, monochrome, b&w, text,  (ugly)++, unclear eyes, no arms,
    bad anatomy, cropped, censoring,  asymmetric eyes, bad anatomy, bad proportions,
    cropped, cross-eyed,  deformed, extra arms, extra fingers, extra limbs, fused
    fingers,  jpeg artifacts, malformed, mangled hands, misshapen body, missing arms,  missing
    fingers, missing hands, missing legs, poorly drawn, tentacle finger,  too many
    arms, too many fingers, watermark, signature, illustration, painting,  anime,
    cartoon
  themes: [
    "a tranquil Japanese zen garden", "a futuristic neon cityscape", "a surreal dreamscape", "a vast desert",
    "an icy tundra", "a lush rainforest", "a magical underwater world", "a bustling medieval marketplace",
    "a volcanic landscape", "a steampunk cityscape", "an enchanted forest", "a celestial space scene",
    "a post-apocalyptic wasteland", "a vibrant alien planet", "a mystical ancient forest", "a massive underground cavern",
    "a sprawling futuristic space station", "an abandoned theme park", "a serene alpine lake", "a dense fog-covered marshland",
    "a grand futuristic library", "a post-apocalyptic cityscape", "a tropical rainforest", "a peaceful icy archipelago"
  ]
  descriptions: [
    "at sunrise", "at sunset", "under the aurora borealis", "at twilight", "during a thunderstorm",
    "under a golden sky", "with glowing bioluminescent plants", "with cascading waterfalls", "with intricate carvings",
    "with overgrown ruins", "with futuristic technology", "with shafts of sunlight piercing through",
    "with vibrant coral reefs", "with swirling nebulae in the sky", "with ancient trees", "with soft mist rolling through",
    "with dynamic lighting", "under a sky filled with stars", "with glowing mushrooms", "with floating islands",
    "over a frozen ocean", "with towering shelves of glowing books"
  ]
  styles:
    cinematic:
      details: [
        "cinematic lighting", "cinematic composition", "cinematic atmosphere", "cinematic style", "cinematic colors",
        "cinematic camera angles", "cinematic depth of field", "cinematic focus", "cinematic motion blur",
      ]
      awards: ["Oscar Nominated", "Best Visual Effects Award"]
    digital_art:
      details: [
        "ultra-detailed", "dramatic atmosphere", "vibrant and colorful", "exotic and imaginative", "high-tech and sleek",
        "3D rendered", "Octane Render", "Cycles", "Blender", "3D Studio Max", "Unreal Engine", "Unity", "Houdini",
        "Substance Painter"
      ]
      awards: ["Trending on ArtStation", "CG Society Awards Winner"]
    renaissance:
      details: [
        "Italian Renaissance style", "sfumato technique", "chiaroscuro lighting", "oil painting texture",
        "classical composition", "Florentine school", "golden ratio composition", "masterful drapery",
        "religious iconography", "architectural perspective", "Venetian color palette", "tempera on wood"
      ]
      awards: ["Classical Art Revival Award", "Renaissance Masters Tribute"]
    painting:
      details: [
        "digital painting", "digital illustration", "serene and peaceful", "soft and tranquil", "lush and vibrant",
        "nostalgic yet eerie", "dynamic and vivid", "dark yet beautiful"
      ]
      awards: ["Digital Art Masters Winner", "ImagineFX Artist of the Month"]
    photo:
      details: [
        "hyper-realistic", "cinematic HDR lighting", "shot on Sony A7R IV", "Zeiss 55mm f1.4", "shot on Canon EOS R5",
        "shot on Nikon Z9", "shot on Fujifilm X-T4"
      ]
      awards: ["Sony World Photography Awards Winner", "National Geographic Photo of the Day"]
    anime:
      details: [
        "anime style", "manga art", "cel shaded", "Studio Ghibli inspired", "J-animation", "kawaii aesthetic",
        "anime lighting", "sharp line art", "vibrant anime colors"
      ]
      awards: ["Anime & Manga Awards Winner", "Japan Media Arts Festival Selection"]
    concept_art:
      details: [
        "professional concept art", "entertainment design", "key art", "production design", "environmental concept",
        "character design", "industry standard", "cinematic composition"
      ]
      awards: ["Spectrum Fantasy Art Award", "Industry Choice Award"]
    pixel_art:
      details: [
        "16-bit style", "32-bit style", "retro gaming aesthetic", "pixel perfect", "limited palette", "dithering",
        "sprite art style", "isometric pixel art"
      ]
      awards: ["Pixel Art Festival Winner", "Retro Gaming Art Award"]
    watercolor:
      details: [
        "watercolor technique", "wet on wet", "flowing colors", "traditional media simulation", "organic textures",
        "soft color bleeding", "painterly style"
      ]
      awards: ["Traditional Media Excellence", "Watercolor Society Selection"]
    minimalist:
      details: [
        "clean design", "minimal composition", "geometric shapes", "limited color palette", "negative space",
        "modern simplicity", "elegant minimalism"
      ]
      awards: ["Modern Design Award", "Minimalist Art Selection"]
  resolutions: ["8k", "16k", "32k", "HDR"]
