display:
  windowed_width: 1024
  windowed_height: 600
  fps: 30
  background_color:
  - 0
  - 0
  - 0
api:
  width: 640
  height: 360
  url: http://orinputer.local:7860/sdapi/v1/txt2img
  background_color:
  - 75
  - 75
  - 75
  background_darkness_variation: 0.2
  checkpoint: revAnimated_v2Pruned_393004
clock:
  radius_margin: 20
  marker_length: 30
  hour_hand_length_ratio: 0.7
  minute_hand_length_ratio: 0.8
  second_hand_length_ratio: 0.9
  numbered_hand_reduction: 0.2
  overlay_opacity: 75
  hour_hand_width:
  - 24
  - 1
  minute_hand_width:
  - 16
  - 1
  second_hand_width:
  - 4
  - 1
  marker_width: 3
  use_numbers: true
  font_size: 36
  display_mode: render_only
animation:
  transition_duration: 3.0
  background_update_interval: 15
  morph_flow_params:
    pyr_scale: 0.5
    levels: 3
    winsize: 15
    iterations: 3
    poly_n: 5
    poly_sigma: 1.2
    flags: 0
