display:
  windowed_width: 1024
  windowed_height: 600
  fps: 30
  background_color: [70, 70, 70]
render:
  width: 640
  height: 360
  background_darkness_variation: 0.2
  checkpoint: models/abstractPhoto_abcevereMix.safetensors
  checkpoints:
    - models/abstractPhoto_abcevereMix.safetensors
    - models/revAnimated_v2Rebirth.safetensors
  models:
    vae: stabilityai/sd-vae-ft-mse
    controlnet: lllyasviel/control_v11f1e_sd15_tile
    default_model:
      url: https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned.safetensors
      path: models/sd-v1-5.safetensors
  generation:
    num_inference_steps: 12
    guidance_scale: 7
    controlnet_conditioning_scale: 1.0
    control_guidance_start: 0.05
    control_guidance_end: 0.9
system:
  shutdown_cmd: sudo /sbin/shutdown -h now
  restart_cmd: sudo /sbin/shutdown -r now
clock:
  radius_margin: 20
  marker_length: 30
  hour_hand_length_ratio: 0.7
  minute_hand_length_ratio: 0.9
  second_hand_length_ratio: 0.9
  numbered_hand_reduction: 0.2
  overlay_opacity: 75
  hour_hand_width: [24, 1]
  minute_hand_width: [16, 1]
  second_hand_width: [4, 1]
  marker_width: 3
  use_numbers: true
  font_size: 36
  display_mode: render_only
animation:
  transition_duration: 3.0
  background_update_interval: 15
  morph_flow_params:
    pyr_scale: 0.5
    levels: 3
    winsize: 15
    iterations: 3
    poly_n: 5
    poly_sigma: 1.2
    flags: 256
